min_caml_print_newline:
min_caml_print_int:
min_caml_print_byte:
  out r2
  blr
min_caml_prerr_int:
min_caml_prerr_byte:
	out r2
	blr
#min_caml_prerr_float:
min_caml_read_int:
min_caml_read_float:
min_caml_create_array:
min_caml_create_float_array:
min_caml_abs_float:
min_caml_sqrt:
min_caml_floor:
min_caml_int_of_float:
min_caml_truncate:
min_caml_float_of_int:
min_caml_cos:
min_caml_sin:
min_caml_atan:
